### ISSUE TITLE
Error when using the "earwax game main.py command."

### ISSUE THREAD

**Issue by ashleygrobler04** [chrisnorman7/earwax#16]
Hi there.
So i red through the tutorials, actually i am at the first one, "getting started."
It told me to use the command "earwax game main.py."
I used it, and got the following error:
ImportError: cannot import name 'cmd_main' from 'earwax' (c:\python\lib\site-packages\earwax\__init__.py)
Maby it's some thing i am doing wrong, but i doubt it, since i typed "earwax game main.py" in the prompt to make the first starter game.

**Comment by chrisnorman7** [comment]
OK, I need to make templates for these things.
Can you give me your earwax version (`pip show earwax`), and Python version please?

Do any of the other commands work for you?

Thank you for reporting.

**Comment by ashleygrobler04** [comment]
Hi there, I feel like a bit of an ape...
I updated earwax and it seemed to be working...
Haha i am sure every person who uses a library should know to first update the lib or in this case engine, before using it right?
Once again, sorry for the unnessiciry issue that was created.

**Comment by chrisnorman7** [comment]
That's absolutely no worries mate. Glad it's working for you.

The new bug template should remind people to update, so you actually helped me a lot more than you probably realised, by reminding me to create issue templates.
