### ISSUE TITLE
Topdown walking

### ISSUE THREAD

**Issue by shadowpates** [chrisnorman7/earwax#22]
Hi!
In my head, I created interesting idea. You played in games like manamon? If yes, you know how to walk in these games?
Is possible to add walking across the rooms using arrows?

**Comment by chrisnorman7** [comment]
Hi,
Firstly, this issue is now closed, and suggestions for other issues don't
go here, as that doesn't help organisation the information.

Secondly, I'm working on a map editor, which will give you 2d
movement, just not top-down like you're talking about.

Take care,

Chris Norman

**Comment by shadowpates** [comment]
Ok, great!

**Comment by chrisnorman7** [comment]
OK, actually, my apologies, I didn't bother checking the subject of the email. I thought you were still replying to #21.

As I said above though, the map editor will give you proper 2d games, and I have no interest in making the Earwax Story builder into something akin to Sable.
